# Generated by Django 4.2.4 on 2023-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('bale_origin', models.CharField(max_length=100)),
                ('store_owner', models.CharField(max_length=100)),
                ('bale_weight', models.DecimalField(decimal_places=1, default=40, max_digits=3)),
            ],
        ),
    ]
