# Generated by Django 4.2.4 on 2024-01-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bales', '0002_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
